project_name: stocks-notifier

before:
  hooks:
    - go mod tidy

builds:
  - id: stocks-notifier
    main: ./stocks-notifier.go
    binary: stocks-notifier
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  skip: true
